### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by jakiestfu** [cobyism/gridism#10]
Great work, mate. I am building an internal frontend framework for the company I work with and we are looking for a no bullshit, no frills, aesthetic grid system, and this seems to be it.

We are writing our core code in SCSS, do you plan to have support for SCSS in the future at all?

Also, what is the browser support on this? I think that should be included somewhere. Thanks!

**Comment by robertcedwards** [comment]
Had the same questions, great conversation solved it all for me. Thanks! :+1:

**Comment by durasj** [comment]
Hey,

I still think it would be great to have scss support. One of the things I had to add myself just now was variable gutter.
