### ISSUE TITLE
Vertical align??

### ISSUE THREAD

**Issue by danielk1260** [cobyism/gridism#25]
How to get a vertical align i have only one div with a class whole for design of my login systen but how to align vertical?

**Comment by tomicakorac** [comment]
Hi Coby, and thanks for the awesome library. It keeps saving me hundreds of work hours :)

Have you considered using `flex box` for this? It seems to be the perfect generic solution for many problems, albeit not entirely supported by legacy browsers. Have a look [at this](https://philipwalton.github.io/solved-by-flexbox/demos/vertical-centering/). Flexbox seems to also solve, among others, the problem of [sticky footer](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/). This [here](https://philipwalton.github.io/solved-by-flexbox/) is a great resource to look at.

I'm considering cloning your Gridism and adopting `flex box`. Once I do, I'll let you know and you can see hot it goes.

**Comment by cobyism** [comment]
Yep, flexbox is great! When I originally started this, browser support still wasn’t great for flexbox though.
