### ISSUE TITLE
Making divs the same height

### ISSUE THREAD

**Issue by gyventi** [cobyism/gridism#42]
I love this gid. Simple and very clean. I am having trouble figuring this out on my own. How can I make two or more divs on the same row, equal in height without writing additional classes for each div.

Also, Is it possible to make a unit div on the right stack on top of another on the left. The opposite of the default stacking order basically.

Thanks!

**Comment by cobyism** [comment]
This grid system was created almost 5 years ago now, and basically everything you can do with it  and more (including specifying how the order that things stack, as you describe above, etc) can be achieved using Flexbox instead. A good guide to getting started with Flexbox can be found here: https://css-tricks.com/snippets/css/a-guide-to-flexbox/
